name: learn_objectbox
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  objectbox: ^2.5.1

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  objectbox_generator: ^2.5.1

flutter: 
  uses-material-design: true

